"""Console entry point for qminweight.

Usage::

    qminweight [INPUT] [options]

INPUT is a file of Pauli stabiliser strings, ``-`` for stdin, or omitted when the code
is supplied via ``--hx/--hz``, ``--classical`` or ``--builtin``. By default the minimum
distance is printed to stdout; ``--json`` prints a JSON object instead.
"""
from __future__ import annotations

import argparse
import json
import sys

from . import api, io


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="qminweight",
        description="Compute the minimum distance of a quantum (CSS) or classical code.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "input sources (choose one):\n"
            "  INPUT                Pauli stabiliser strings from a file, or '-' for stdin\n"
            "  --hx FILE --hz FILE  X and Z parity-check matrices (0/1 text or .mtx)\n"
            "  --classical FILE     a single classical parity-check matrix\n"
            "  --builtin NAME[:L]   a generator from qminweight.codes "
            "(steane, shor, toric:L,\n"
            "                       surface:L, gross, repetition:L, hamming:L)\n"
            "\nexamples:\n"
            "  qminweight --builtin steane\n"
            "  qminweight --builtin gross --method cc\n"
            "  cat code.txt | qminweight -\n"
            "  qminweight --hx Hx.txt --hz Hz.txt --zx\n"
            "  qminweight --hx Gx.txt --hz Gz.txt --subsystem   # dressed distance\n"
            "  qminweight --builtin steane --operator ZZZZZZZ   # operator weight\n"
        ),
    )
    p.add_argument("input", nargs="?", default=None,
                   help="Pauli stabiliser file, or '-' for stdin")
    p.add_argument("--hx", metavar="FILE", help="X parity-check matrix file")
    p.add_argument("--hz", metavar="FILE", help="Z parity-check matrix file")
    p.add_argument("--classical", metavar="FILE",
                   help="single classical parity-check matrix file")
    p.add_argument("--symplectic", metavar="FILE",
                   help="symplectic stabiliser matrix (0/1 text, 2n columns in [z|x] "
                        "order) for a general non-CSS code")
    p.add_argument("--builtin", metavar="NAME[:L]",
                   help="use a built-in code generator")

    p.add_argument("--method", choices=["bz", "cc", "mitm"], default="bz",
                   help="distance algorithm (default: bz)")
    p.add_argument("--backend", choices=["auto", "cpu", "gpu"], default="auto",
                   help="compute backend; gpu auto-selects the available accelerator "
                        "(default: auto)")
    p.add_argument("--which", choices=["min", "z", "x"], default="min",
                   help="CSS component to report (default: min)")
    p.add_argument("--threads", type=int, default=0, metavar="N",
                   help="CPU worker threads (0 => hardware concurrency)")
    p.add_argument("--max-weight", type=int, default=0, metavar="N", dest="max_weight",
                   help="safety cap on enumeration weight (0 => none)")

    p.add_argument("--subsystem", action="store_true",
                   help="treat the X/Z input as GAUGE generators of a CSS subsystem "
                        "code and report its dressed distance")
    p.add_argument("--operator", metavar="STR", default=None,
                   help="a Pauli string (I/X/Y/Z/._); report its weight modulo the "
                        "group generated by the input (use --subsystem for a gauge group)")

    p.add_argument("--json", action="store_true",
                   help="emit a JSON object instead of a bare integer")
    p.add_argument("--zx", action="store_true",
                   help="CSS: print '<dZ> <dX>' (or both in JSON)")
    p.add_argument("-v", "--verbose", action="store_true",
                   help="verbose diagnostics on stderr")
    p.add_argument("--list-backends", action="store_true",
                   help="list usable backends and exit")
    p.add_argument("--version", action="store_true",
                   help="print the qminweight version and exit")
    return p


def _resolve_input(args):
    """Return ('css', Hx, Hz), ('stab', S, None) or ('classical', H, None) from the
    chosen input source. 'stab' is a symplectic [z|x] matrix for a non-CSS code."""
    sources = [bool(args.hx or args.hz), bool(args.classical), bool(args.builtin),
               bool(args.symplectic)]
    if sum(sources) > 1:
        raise ValueError("choose only one of --hx/--hz, --classical, "
                         "--symplectic, --builtin")

    if args.builtin:
        return io.load_builtin(args.builtin)

    if args.symplectic:
        S = io.load_matrix(args.symplectic)
        if S.shape[1] % 2 != 0:
            raise ValueError("symplectic matrix must have 2n (even) columns")
        return "stab", S, None

    if args.classical:
        return "classical", io.load_matrix(args.classical), None

    if args.hx or args.hz:
        if not (args.hx and args.hz):
            raise ValueError("--hx and --hz must be given together")
        Hx = io.load_matrix(args.hx)
        Hz = io.load_matrix(args.hz)
        if Hx.shape[1] != Hz.shape[1]:
            raise ValueError("Hx and Hz have differing column counts "
                             "(different number of qubits)")
        return "css", Hx, Hz

    # default: Pauli stabiliser strings from INPUT (file or stdin). A code with a Y or a
    # row mixing X and Z is non-CSS -> parse into a symplectic [z|x] matrix.
    text = io.read_text(args.input)
    if io.is_css_pauli(text):
        Hx, Hz = io.parse_pauli(text)
        return "css", Hx, Hz
    return "stab", io.parse_stabilizers(text), None


def _emit(result, *, which_label, json_out, zx, second=None):
    """Print a Result (or a pair for --zx) to stdout."""
    if zx:
        z, x = result, second
        if json_out:
            print(json.dumps({
                "dZ": z.distance, "dX": x.distance,
                "dZ_lower_bound": z.lower_bound, "dX_lower_bound": x.lower_bound,
                "proven": bool(z.proven and x.proven),
                "seconds": z.seconds + x.seconds,
                "backend": z.backend,
            }))
        else:
            for r, lbl in ((z, "dZ"), (x, "dX")):
                if not r.proven:
                    print("qminweight: %s in [%d, %d] (not proven)"
                          % (lbl, r.lower_bound, r.distance), file=sys.stderr)
            print("%d %d" % (z.distance, x.distance))
        return

    if json_out:
        print(json.dumps({
            "distance": result.distance,
            "lower_bound": result.lower_bound,
            "proven": bool(result.proven),
            "seconds": result.seconds,
            "backend": result.backend,
            "which": which_label,
        }))
    else:
        if not result.proven:
            print("qminweight: %s in [%d, %d] (not proven)"
                  % (which_label, result.lower_bound, result.distance),
                  file=sys.stderr)
        print(result.distance)


def _emit_op(result, *, json_out, zx):
    """Print an OpResult (operator weight) to stdout."""
    if json_out:
        print(json.dumps({
            "z_weight": result.z_weight,
            "x_weight": result.x_weight,
            "weight": result.weight,
            "proven": bool(result.proven),
            "seconds": result.seconds,
            "backend": result.backend,
        }))
    elif zx:
        print("%d %d" % (result.z_weight, result.x_weight))
    else:
        print(result.weight)


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()

    if args.version:
        print(api.version())
        return 0

    if args.list_backends:
        for b in api.available_backends():
            print(b)
        return 0

    try:
        kind, A, B = _resolve_input(args)
    except (ValueError, FileNotFoundError, OSError) as e:
        print("qminweight: %s" % e, file=sys.stderr)
        return 1

    common = dict(method=args.method, backend=args.backend,
                  threads=args.threads, max_weight=args.max_weight,
                  verbose=args.verbose)

    try:
        if kind == "classical":
            if args.subsystem or args.operator is not None:
                print("qminweight: --subsystem/--operator require a CSS code",
                      file=sys.stderr)
                return 1
            if args.zx:
                print("qminweight: --zx is only meaningful for CSS codes",
                      file=sys.stderr)
                return 1
            if args.method == "cc":
                # connected-cluster has no classical entry point in the API
                print("qminweight: --method cc is for CSS codes; use bz or mitm for "
                      "classical codes", file=sys.stderr)
                return 1
            r = api.classical_distance(A, **common)
            _emit(r, which_label="d", json_out=args.json, zx=False)
            return 0

        if kind == "stab":
            # General (non-CSS) stabiliser code given as a symplectic [z|x] matrix.
            S = A
            n = S.shape[1] // 2
            if args.zx:
                print("qminweight: --zx is only meaningful for CSS codes "
                      "(a non-CSS distance is a single number)", file=sys.stderr)
                return 1
            if args.which != "min":
                print("qminweight: --which is only meaningful for CSS codes; reporting "
                      "the full non-CSS distance", file=sys.stderr)

            if args.operator is not None:
                op_common = {k: v for k, v in common.items() if k != "method"}
                r = api.pauli_operator_weight(S, args.operator,
                                              method=args.method, **op_common)
                if args.json:
                    print(json.dumps({"weight": r.weight, "proven": bool(r.proven),
                                      "seconds": r.seconds, "backend": r.backend}))
                else:
                    print(r.weight)
                return 0

            dist = (api.subsystem_stabilizer_distance if args.subsystem
                    else api.stabilizer_distance)
            r = dist(S, which="min", **common)
            label = "d (dressed)" if args.subsystem else "d"
            _emit(r, which_label=label, json_out=args.json, zx=False)
            return 0

        # CSS code
        Hx, Hz = A, B

        # Operator weight: report the weight of a Pauli operator modulo the group
        # generated by the input (gauge group when --subsystem, else stabilizers).
        if args.operator is not None:
            op_common = {k: v for k, v in common.items() if k != "method"}
            r = api.operator_weight(Hx, Hz, args.operator,
                                    method=args.method, **op_common)
            _emit_op(r, json_out=args.json, zx=args.zx)
            return 0

        # Dressed distance of a CSS subsystem code, or ordinary CSS distance.
        dist = api.subsystem_css_distance if args.subsystem else api.css_distance
        if args.zx:
            z = dist(Hx, Hz, which="z", **common)
            x = dist(Hx, Hz, which="x", **common)
            _emit(z, which_label="zx", json_out=args.json, zx=True, second=x)
        else:
            r = dist(Hx, Hz, which=args.which, **common)
            label = {"min": "d", "z": "dZ", "x": "dX"}[args.which]
            _emit(r, which_label=label, json_out=args.json, zx=False)
        return 0
    except (RuntimeError, ValueError) as e:
        print("qminweight: %s" % e, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
